<a href="https://colab.research.google.com/github/RachmadAprisandhy/PembelajaranMesin/blob/main/JS/JS02_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

load library

In [8]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
path = '/content/drive/MyDrive/Pembelajaran mesin/Titanic-Dataset.csv'
df = pd.read_csv(path)

load data

In [11]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

slice data

In [12]:
df = df[['Survived', 'Pclass', 'Age', 'Sex', 'Cabin']]
df.head()

   Survived  Pclass   Age     Sex Cabin
0         0       3  22.0    male   NaN
1         1       1  38.0  female   C85
2         1       3  26.0  female   NaN
3         1       1  35.0  female  C123
4         0       3  35.0    male   NaN

encoding

In [13]:
le = LabelEncoder() # membuat objek dari LabelEncoder
df['Sex'] = le.fit_transform(df['Sex']) # proses encoding
df['Cabin'] = le.fit_transform(df['Cabin']) # proses encoding

Verifikasi Hasil

In [14]:
df.head()

   Survived  Pclass   Age  Sex  Cabin
0         0       3  22.0    1    147
1         1       1  38.0    0     81
2         1       3  26.0    0    147
3         1       1  35.0    0     55
4         0       3  35.0    1    147

Standarisasi

In [16]:
std = StandardScaler()
df['Age'] = std.fit_transform(df[['Age']])

verifikasi hasil standarisasi

In [17]:
df.head()

   Survived  Pclass       Age  Sex  Cabin
0         0       3 -0.530377    1    147
1         1       1  0.571831    0     81
2         1       3 -0.254825    0    147
3         1       1  0.365167    0     55
4         0       3  0.365167    1    147